/**
 * Shared test fixtures for the few tests that spin up the full `buildApp()`
 * via `app.inject()`. Each test file still declares its own `vi.mock(...)`
 * calls (Vitest requires them at the top of the file so they get hoisted) —
 * this helper only holds the object those mocks feed into.
 */
export const defaultTestEnv = {
	NODE_ENV: 'test',
	PORT: 4000,
	DATABASE_URL: 'postgresql://test:test@localhost:5432/test',
	SESSION_SECRET: 'x'.repeat(48),
	SESSION_COOKIE_NAME: 'sid',
	SESSION_IDLE_MS: 7_200_000,
	SESSION_ABSOLUTE_MS: 1_209_600_000,
	SESSION_TOUCH_MIN_INTERVAL_MS: 300_000,
	SHUTDOWN_DRAIN_MS: 15_000,
	COOKIE_SECURE: false,
	COOKIE_SAME_SITE: 'lax',
	GOOGLE_CLIENT_IDS: ['test-client-id'],
	ALLOWED_GOOGLE_HD: '',
	CORS_ALLOWED_ORIGINS: ['http://localhost:5173'],
	API_PUBLIC_URL: 'http://localhost:4000',
	WEB_PUBLIC_URL: 'http://localhost:5173',
	AUTO_PUBLISH_DEFAULT: false,
	LOG_LEVEL: 'silent',
	TRUST_PROXY: 'false',
	RATE_LIMIT_GLOBAL_MAX: 300,
	RATE_LIMIT_GLOBAL_WINDOW_MS: 60_000,
	RATE_LIMIT_LOGIN_MAX: 20,
	RATE_LIMIT_LOGIN_WINDOW_MS: 60_000,
	RATE_LIMIT_SUBMIT_MAX: 30,
	RATE_LIMIT_SUBMIT_WINDOW_MS: 3_600_000,
	UPLOAD_USER_IMAGE_MAX_MB: 10,
	UPLOAD_USER_GAME_MAX_MB: 5120,
	UPLOAD_USER_REQUEST_MAX_MB: 250,
	UPLOAD_USER_MAX_FILES: 10,
	UPLOAD_PRIVILEGED_IMAGE_MAX_MB: 15,
	UPLOAD_PRIVILEGED_GAME_MAX_MB: 5120,
	UPLOAD_PRIVILEGED_REQUEST_MAX_MB: 1200,
	UPLOAD_PRIVILEGED_MAX_FILES: 20,
	UPLOAD_MAX_CONCURRENT: 5,
	UPLOAD_CHUNKED_GAME_MAX_MB: 5120,
	UPLOAD_CHUNK_SIZE_MB: 10,
	UPLOAD_SESSION_TTL_MINUTES: 1440,
	S3_ENDPOINT: 'http://localhost:3900',
	S3_REGION: 'garage',
	S3_ACCESS_KEY_ID: 'test',
	S3_SECRET_ACCESS_KEY: 'test',
	S3_BUCKET_PUBLIC: 'pcu-public',
	S3_BUCKET_PROTECTED: 'pcu-protected',
	S3_FORCE_PATH_STYLE: true,
	S3_PRESIGN_TTL_SEC: 60,
} as const;

export type TestEnv = typeof defaultTestEnv;
