// API 응답/요청 타입은 packages/contracts (@pcu/contracts) 에서 import.
// 여기서는 (a) 공유 transport 타입 re-export + (b) Web-로컬 폼 스키마 wrapper 만 둔다.

export type {
	AssetKind,
	AssetPlaybackStatus,
	Platform,
	ProjectStatus,
	UserRole,
	ApiErrorCode,
	AuthUser,
	DevAuthErrorScenario,
	DevAuthLoginErrorRequest,
	DevAuthLoginRequest,
	GoogleAuthRequest,
	GoogleAuthResponse,
	LogoutResponse,
	MeResponse,
	ProjectVideo,
	PublicExhibition,
	PublicExhibitionProjectsResponse,
	PublicProjectCard,
	PublicProjectDetailResponse,
	PublicProjectImage,
	PublicProjectMember,
	PublicYearItem,
	PublicYearListResponse,
	PublicYearProjectsResponse,
	AdminExhibitionItem,
	CreateExhibitionRequest,
	UpdateExhibitionRequest,
	AddMemberRequest,
	AdminProjectDetail,
	AdminProjectItem,
	AdminProjectListQuery,
	AdminProjectListResponse,
	AdminProjectListSort,
	BulkDeleteProjectsRequest,
	BulkUpdateProjectStatusRequest,
	PaginationInfo,
	SetProjectPosterRequest,
	SortOrder,
	SubmitProjectPayload,
	SubmitProjectResponse,
	SwapProjectMembersRequest,
	UpdateMemberRequest,
	UpdateProjectRequest,
	BannedIpItem,
	BannedIpListResponse,
	SiteSettingsData,
	UpdateSiteSettingsRequest,
	ExportFileStatus,
	ExportPhase,
	ExportProgress,
	ExportProgressFile,
	ExportResult,
	ExportStatusResponse,
	ImportExecuteResult,
	ImportPreviewExhibition,
	ImportPreviewResult,
	GameUploadChunkResponse,
	GameUploadCompleteResponse,
	GameUploadCreateSessionRequest,
	GameUploadSession,
	GameUploadSessionListResponse,
	GameUploadStatus,
} from '@pcu/contracts';
export * from './schemas';

// 폼 옵션 등 런타임 배열은 Web에서 필요한 곳에서 따로 정의한다.
// (예: USER_ROLES = ['USER', 'OPERATOR', 'ADMIN'] as const)
